In [1]:
#!pip3 install h2o

In [2]:
import pandas as pd
import h2o
from h2o.automl import H2OAutoML

In [3]:
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321 . connected.

--------------------------  ------------------------------------------------------------------
H2O cluster uptime:         1 day 23 hours 48 mins
H2O cluster timezone:       Europe/Madrid
H2O data parsing timezone:  UTC
H2O cluster version:        3.28.0.3
H2O cluster version age:    1 month and 6 days
H2O cluster name:           H2O_from_python_santiagobermejo_k9krvh
H2O cluster total nodes:    1
H2O cluster free memory:    1.922 Gb
H2O cluster total cores:    4
H2O cluster allowed cores:  4
H2O cluster status:         locked, healthy
H2O connection url:         http://localhost:54321
H2O connection proxy:       {'http': None, 'https': None}
H2O internal security:      False
H2O API Extensions:         Amazon S3, XGBoost, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python version:             3.8.1 final
--------------------------  ------------------------------------------------------------------

In [4]:
df_final = pd.read_csv('output/dfFinal.csv')

In [5]:
df_final

,Unnamed: 0,GAME_ID,HOME_TEAM_ID_x,VISITOR_TEAM_ID_x,SEASON,HOME_TEAM_WINS,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,VISITOR_TEAM_ID_y,HOME_TEAM_ID_y
0,0,21900895,1610612766,1610612749,2019,VISITANTE,103.193548,0.435516,0.749742,0.338387,23.806452,42.935484,117.424242,0.476030,0.767788,0.350182,24.727273,51.575758,5,4
1,1,21900669,1610612766,1610612749,2019,VISITANTE,103.193548,0.435516,0.749742,0.338387,23.806452,42.935484,117.424242,0.476030,0.767788,0.350182,24.727273,51.575758,5,5
2,2,21900094,1610612750,1610612749,2019,VISITANTE,110.413793,0.427345,0.725655,0.318621,23.551724,47.344828,117.424242,0.476030,0.767788,0.350182,24.727273,51.575758,5,5
3,3,21900111,1610612746,1610612749,2019,VISITANTE,115.705882,0.465588,0.767971,0.367912,24.941176,48.647059,117.424242,0.476030,0.767788,0.350182,24.727273,51.575758,5,3
4,4,21900575,1610612758,1610612749,2019,VISITANTE,109.033333,0.460200,0.750233,0.365400,22.533333,43.100000,117.424242,0.476030,0.767788,0.350182,24.727273,51.575758,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
960,960,21900329,1610612757,1610612747,2019,VISITANTE,115.741935,0.464968,0.811355,0.387452,20.645161,47.064516,113.088235,0.479059,0.694647,0.352441,25.058824,44.882353,4,4
961,961,21900667,1610612751,1610612747,2019,VISITANTE,110.580645,0.457226,0.717032,0.365387,24.064516,48.741935,113.088235,0.479059,0.694647,0.352441,25.058824,44.882353,5,3
962,962,11900044,1610612751,1610612747,2019,LOCAL,110.580645,0.457226,0.717032,0.365387,24.064516,48.741935,113.088235,0.479059,0.694647,0.352441,25.058824,44.882353,5,5
963,963,21900572,1610612742,1610612747,2019,VISITANTE,115.437500,0.460062,0.777656,0.364187,24.187500,46.812500,113.088235,0.479059,0.694647,0.352441,25.058824,44.882353,4,3
964,964,21900074,1610612742,1610612747,2019,VISITANTE,115.437500,0.460062,0.777656,0.364187,24.187500,46.812500,113.088235,0.479059,0.694647,0.352441,25.058824,44.882353,5,4

In [6]:
y = df_final.HOME_TEAM_WINS

In [7]:
X = df_final.drop(columns =['Unnamed: 0','HOME_TEAM_WINS','SEASON','GAME_ID'])

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [9]:
train = pd.concat([X_train, y_train], axis=1, sort=False)

In [10]:
test = pd.concat([X_test, y_test], axis=1, sort=False)

In [11]:
test

,HOME_TEAM_ID_x,VISITOR_TEAM_ID_x,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,VISITOR_TEAM_ID_y,HOME_TEAM_ID_y,HOME_TEAM_WINS
276,1610612745,1610612760,119.774194,0.452968,0.765355,0.342548,22.129032,47.645161,106.344828,0.451552,0.787966,0.340207,20.586207,43.551724,3,4,VISITANTE
949,1610612756,1610612747,112.058824,0.467853,0.812529,0.345206,26.617647,43.264706,113.088235,0.479059,0.694647,0.352441,25.058824,44.882353,5,4,VISITANTE
615,1610612737,1610612750,113.060606,0.457485,0.781727,0.340939,24.303030,44.272727,114.705882,0.442529,0.767147,0.342882,23.941176,43.882353,5,5,VISITANTE
196,1610612743,1610612754,111.687500,0.481719,0.745875,0.348719,27.531250,44.750000,109.333333,0.480133,0.781500,0.378767,26.266667,41.400000,3,3,VISITANTE
743,1610612743,1610612746,111.687500,0.481719,0.745875,0.348719,27.531250,44.750000,114.241379,0.459483,0.795517,0.358414,23.172414,46.310345,4,4,LOCAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
819,1610612756,1610612743,112.058824,0.467853,0.812529,0.345206,26.617647,43.264706,109.781250,0.461187,0.799563,0.354688,25.343750,44.468750,5,4,VISITANTE
331,1610612761,1610612758,115.705882,0.467059,0.801118,0.380265,26.176471,46.117647,108.735294,0.454853,0.774412,0.360500,24.147059,41.705882,4,5,LOCAL
39,1610612737,1610612752,113.060606,0.457485,0.781727,0.340939,24.303030,44.272727,104.937500,0.440969,0.698406,0.349375,21.406250,46.718750,4,3,LOCAL
617,1610612739,1610612750,107.515152,0.461061,0.775030,0.359788,23.303030,44.545455,114.705882,0.442529,0.767147,0.342882,23.941176,43.882353,4,2,VISITANTE
837,1610612746,1610612757,115.705882,0.465588,0.767971,0.367912,24.941176,48.647059,110.294118,0.455324,0.765059,0.348294,19.441176,44.352941,4,4,LOCAL

In [12]:
h2train = h2o.H2OFrame(train)
h2test = h2o.H2OFrame(test)

Parse progress: |█████████████████████████████████████████████████████████| 100%
Parse progress: |█████████████████████████████████████████████████████████| 100%

In [13]:
columnas = [a for a in h2train.columns if a != 'HOME_TEAM_WINS']
x = columnas
y = 'HOME_TEAM_WINS'
print(columnas)

['HOME_TEAM_ID_x', 'VISITOR_TEAM_ID_x', 'PTS_home', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home', 'REB_home', 'PTS_away', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away', 'AST_away', 'REB_away', 'VISITOR_TEAM_ID_y', 'HOME_TEAM_ID_y']

In [14]:
automl = H2OAutoML(max_models=50, seed=42,max_runtime_secs=300, sort_metric='RMSE')
automl.train(x=x, y=y, training_frame=h2train)

AutoML progress: |████████████████████████████████████████████████Failed polling AutoML progress log: Unexpected HTTP error: ('Connection aborted.', BadStatusLine('POST /99/Rapids HTTP/1.1\r\n'))
████████| 100%

In [15]:
print('[INFO] Models leader board:')
leader_board = automl.leaderboard
leader_board.head()

[INFO] Models leader board:

model_id,rmse,auc,logloss,aucpr,mean_per_class_error,mse
XGBoost_2_AutoML_20200312_115435,0.462497,0.71219,0.614859,0.647794,0.356432,0.213904
GLM_1_AutoML_20200312_115435,0.462614,0.712475,0.61411,0.660052,0.335369,0.214012
XGBoost_1_AutoML_20200312_115435,0.463775,0.709284,0.617556,0.635255,0.359907,0.215087
XGBoost_grid__1_AutoML_20200312_115435_model_1,0.464648,0.707103,0.619151,0.640648,0.387632,0.215897
GBM_5_AutoML_20200312_115435,0.464704,0.707201,0.619889,0.643899,0.386379,0.215949
StackedEnsemble_BestOfFamily_AutoML_20200312_115435,0.464783,0.710006,0.620264,0.648966,0.332145,0.216024
GBM_grid__1_AutoML_20200312_115435_model_5,0.464879,0.70646,0.619042,0.639138,0.380218,0.216112
XGBoost_3_AutoML_20200312_115435,0.465045,0.707316,0.620439,0.633227,0.374522,0.216267
GBM_grid__1_AutoML_20200312_115435_model_9,0.465081,0.706209,0.6202,0.63997,0.379788,0.2163
XGBoost_grid__1_AutoML_20200312_115435_model_3,0.465585,0.706385,0.622606,0.646029,0.353851,0.216769

In [16]:
metrics = automl.leader.cross_validation_metrics_summary().as_data_frame()
metrics

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,accuracy,0.6723754,0.047680873,0.59354836,0.67741936,0.6753247,0.72077924,0.6948052
1,auc,0.71755695,0.03200632,0.67109245,0.72753185,0.6996744,0.7492832,0.7402027
2,aucpr,0.6454702,0.076324865,0.6136352,0.6683983,0.5374302,0.7442664,0.6636208
3,err,0.32762462,0.047680873,0.4064516,0.32258064,0.32467532,0.2792208,0.3051948
4,err_count,50.6,7.5033326,63.0,50.0,50.0,43.0,47.0
5,f0point5,0.63589835,0.059911806,0.57894737,0.6418219,0.5753425,0.7160494,0.6673307
6,f1,0.69726473,0.046108667,0.6769231,0.7126437,0.6268657,0.7295597,0.7403315
7,f2,0.77584565,0.0589275,0.8148148,0.8010336,0.6885246,0.74358976,0.8312655
8,lift_top_group,1.5261301,0.48157233,1.1071428,1.0915493,1.3508772,2.0,2.0810812
9,logloss,0.6148409,0.015837613,0.63956326,0.6037406,0.62131244,0.60124797,0.6083403
10,max_per_class_error,0.47094518,0.14868887,0.69411767,0.48809522,0.36082473,0.3116883,0.5
11,mcc,0.39303917,0.0549253,0.31331962,0.406417,0.36311188,0.44249234,0.43985504
12,mean_per_class_accuracy,0.68568647,0.036515743,0.62436974,0.6925721,0.68800867,0.72077924,0.7027027
13,mean_per_class_error,0.3143135,0.036515743,0.37563026,0.3074279,0.3119913,0.2792208,0.2972973
14,mse,0.21389481,0.007504103,0.22582734,0.20872769,0.21656133,0.20766707,0.21069065
15,pr_auc,0.6454702,0.076324865,0.6136352,0.6683983,0.5374302,0.7442664,0.6636208
16,precision,0.6017763,0.07132484,0.528,0.60194176,0.54545456,0.70731705,0.62616825
17,r2,0.12873979,0.045514263,0.08815096,0.15917462,0.07108546,0.16933174,0.1559562
18,recall,0.8423182,0.09233516,0.94285715,0.87323946,0.7368421,0.7532467,0.9054054
19,rmse,0.46243143,0.008060083,0.47521293,0.45686725,0.4653615,0.45570502,0.4590105
20,specificity,0.5290548,0.14868887,0.30588236,0.5119048,0.63917524,0.6883117,0.5

In [17]:
automl.leader.varimp(use_pandas=True)

             variable  relative_importance  scaled_importance  percentage
0         FG_PCT_home           367.268768           1.000000    0.206321
1            PTS_home           225.692230           0.614515    0.126787
2        FG3_PCT_away           169.982544           0.462829    0.095491
3            REB_home           135.059982           0.367742    0.075873
4            REB_away           122.502159           0.333549    0.068818
5         FG_PCT_away           121.166023           0.329911    0.068068
6            PTS_away           116.916779           0.318341    0.065680
7            AST_away           113.535957           0.309136    0.063781
8        FG3_PCT_home           102.028732           0.277804    0.057317
9         FT_PCT_home            98.562378           0.268366    0.055369
10           AST_home            74.665489           0.203299    0.041945
11        FT_PCT_away            73.436958           0.199954    0.041255
12  VISITOR_TEAM_ID_y            52.534592           0.143041    0.029512
13     HOME_TEAM_ID_y             6.732527           0.018331    0.003782

In [18]:
predictions = automl.leader.predict(h2test)

xgboost prediction progress: |████████████████████████████████████████████| 100%

In [19]:
h2o.save_model(automl.leader, path='./mymodel')

'/Users/santiagobermejo/Desktop/IRONHACK/Proyecto-Final/mymodel/XGBoost_2_AutoML_20200312_115435'

In [21]:
model_path= '/Users/santiagobermejo/Desktop/IRONHACK/Proyecto-Final/mymodel/XGBoost_2_AutoML_20200312_115435'
saved_model = h2o.load_model(model_path)